---
title: "Landing sites"
output: html_notebook
---


```{r load package, include=FALSE}
#rebuild and load the package
devtools::load_all() # restarts and loads

# List of packages for session
.packages = c("import")

# Install CRAN packages (if not already installed)
.inst <- .packages %in% installed.packages()
if(length(.packages[!.inst]) > 0) install.packages(.packages[!.inst])

# Load packages into session 
lapply(.packages, require, character.only=TRUE)

#use this for packages
#specifies what functions to import
# https://cran.r-project.org/web/packages/import/vignettes/import.html
import::from(dplyr, mutate, distinct, select, group_by, summarise, keep_when = filter)

```

#Create table georeferrenced locations
```{r location table, echo=FALSE}
googlesheets4::gs4_deauth()

ents.coast.selecc <- toupper(c("Baja California Sur", "Baja California", "Sonora", "Sinaloa", "Nayarit", "Jalisco"))
coast.selecc <- stringi::stri_trans_general(str = ents.coast.selecc, id = "Latin-ASCII")

inegi.cost.comm.all  <- readr::read_csv(paste0("~/coastalvulnerability-inputs/processed_data/all_coastal_communities_INEGI.csv")) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_MUN = stringi::stri_trans_general(str = NOM_MUN, id = "Latin-ASCII"), NOM_MUN = toupper(NOM_MUN)) %>% 
  mutate(NOM_LOC = stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC)) %>% 
  keep_when(NOM_ENT %in% coast.selecc) 

inegi.cost.geo <- inegi.cost.comm.all %>% 
  dplyr::arrange(NOM_ENT, NOM_MUN, NOM_LOC) %>% 
  dplyr::group_by(NOM_ENT, NOM_LOC, NOM_MUN) %>% 
  summarise(deci_lat = mean(deci_lat), deci_lon = mean(deci_lon))


inegi.cost.geo.dis <- inegi.cost.geo %>% 
  dplyr::left_join(inegi.cost.comm.all, by = c("NOM_ENT", "NOM_MUN","NOM_LOC"))

inegi.cost.ent.loc <- inegi.cost.comm.all %>% 
 distinct(NOM_ENT, NOM_LOC) 

#test for duplicates 
dupes.inegi <- inegi.cost.comm.all %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  mutate(dupe = dplyr::n()>1) %>% 
  keep_when(dupe == TRUE)

#difference in locs.inegi

locs.inegi <- googlesheets4::read_sheet("1Nww_0aSf2yQv9YqK8LqmJmIM2wwpHZCSpG1NcGfIfHQ", sheet = "busqueda_inegi") %>% 
  dplyr::rename(deci_lat=latitud, deci_lon=longitud) %>% 
  keep_when(utilizar == 1) %>% 
  keep_when(NOM_ENT %in% coast.selecc) %>% 
  select(NOM_ENT, NOM_LOC, deci_lat, deci_lon)

#test for duplicates 
dupes.inegi <- locs.inegi %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  mutate(dupe = dplyr::n()>1) %>% 
  keep_when(dupe == TRUE)

#to eliminate duplicates get the mean of the lat and lon
locs.inegi.dis <- locs.inegi %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  summarise(deci_lat = mean(deci_lat), deci_lon = mean(deci_lon))

locs.inegi.ent.loc <- locs.inegi.dis %>% 
  distinct(NOM_ENT, NOM_LOC) 

diff.inegi <- dplyr::setdiff(locs.inegi.ent.loc, inegi.cost.ent.loc)

locs.inegi.add <- diff.inegi %>% 
  dplyr::left_join(locs.inegi.dis, by = c("NOM_ENT", "NOM_LOC")) %>% 
  mutate(source= "inegi")

locs.google <- googlesheets4::read_sheet("1Nww_0aSf2yQv9YqK8LqmJmIM2wwpHZCSpG1NcGfIfHQ", sheet = "busqueda_google") %>% 
  dplyr::rename(NOM_LOC=NOM_LOC_REV, deci_lat=lat, deci_lon=lon) %>% 
  keep_when(NOM_ENT %in% coast.selecc) %>% 
  keep_when(utilizar == 1) %>% 
  select(NOM_ENT, NOM_LOC, deci_lat, deci_lon) %>% 
  mutate(deci_lon=as.numeric(deci_lon), deci_lat=as.numeric(deci_lat))

#test for duplicates 
dupes.google <- locs.google %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  mutate(dupe = dplyr::n()>1)

#no duplicates present, only get difference from INEGI

locs.google.ent.loc <- locs.google %>% 
  distinct(NOM_ENT, NOM_LOC) 

diff.google <- dplyr::setdiff(locs.google.ent.loc, inegi.cost.ent.loc)

locs.google.add <- diff.google %>% 
  dplyr::left_join(locs.google, by = c("NOM_ENT", "NOM_LOC")) 

#Atlas fishing locations Pacific
locs.pesca.pacifico <- googlesheets4::read_sheet("1KxO30FqYed655frJDiLobx3N-slFNpNLpHnbxE4cLcI") %>% 
  dplyr::rename(NOM_ENT= ESTADO, NOM_LOC = LOCALIDAD_REVISADA) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_LOC = stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC)) %>% 
  select(-LOCALIDAD_ORIGINAL, -ID) %>% 
  dplyr::rename(deci_lat =LATITUD, deci_lon=LONGITUD) %>% 
  keep_when(NOM_ENT %in% coast.selecc)

#test for duplicates 
dupes.pacifico <- locs.pesca.pacifico %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  mutate(dupe = dplyr::n()>1)

#to eliminate duplicates get the mean of the lat and lon
locs.pacifico.dis <- locs.pesca.pacifico %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  summarise(deci_lat = mean(deci_lat), deci_lon = mean(deci_lon))

#get difference from INEGI

locs.pacifico.ent.loc <- locs.pacifico.dis %>% 
  distinct(NOM_ENT, NOM_LOC) 

diff.pacifico <- dplyr::setdiff(locs.pacifico.ent.loc, inegi.cost.ent.loc)

locs.pacifico.add <- diff.pacifico %>% 
  dplyr::left_join(locs.pacifico.dis, by = c("NOM_ENT", "NOM_LOC")) 

#combine all locations
georef.locs <- dplyr::bind_rows(inegi.cost.comm.all, locs.inegi.add, locs.google.add, locs.pacifico.add) %>% 
  distinct(NOM_ENT, NOM_LOC, deci_lat, deci_lon) 

#test for duplicates 
dupes.georef.locs <- georef.locs %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  mutate(dupe = dplyr::n()>1) %>% 
  keep_when(dupe == TRUE)


georef.locs.all <- georef.locs %>%
  keep_when(NOM_ENT %in% coast.selecc) %>% 
  group_by(NOM_ENT, NOM_LOC) %>%
  summarise(deci_lat = mean(deci_lat), deci_lon = mean(deci_lon))

readr::write_csv(georef.locs.all, here::here("outputs","georef_locations.csv"))


```



Extract permit information from the Registro Nacional de Pesca y Acuacultura RNPA 
https://www.gob.mx/conapesca/documentos/registro-nacional-de-pesca-y-acuacultura-rnpa

```{r get catch, message=TRUE, warning=TRUE, include=FALSE}

georef.locs.all <- readr::read_csv(here::here("outputs","georef_locations.csv")) %>% 
  dplyr::rename(dec_lat_google = deci_lat, dec_lon_google = deci_lon)


#googlesheet to keep track of names that need correction
#vulnerability_tables
    
googlesheets4::gs4_deauth()

 locs.pesca <- googlesheets4::read_sheet("1eJXjwlHqEzSAZaTmE_XyN93fu6EI0I8igRH4AdvXOl8") %>% 
  mutate(NOM_LOC= stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC)) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_LOC_REV= stringi::stri_trans_general(str = NOM_LOC_REV, id = "Latin-ASCII"), NOM_LOC_REV = toupper(NOM_LOC_REV)) %>% 
  mutate(NOM_ENT_REV= stringi::stri_trans_general(str = NOM_ENT_REV, id = "Latin-ASCII"), NOM_ENT_REV = toupper(NOM_ENT_REV)) %>%
   distinct(NOM_LOC, NOM_ENT, NOM_LOC_REV, NOM_ENT_REV) %>% 
   keep_when(!is.na(NOM_LOC_REV))

ents.coast.selecc <- toupper(c("Baja California Sur", "Baja California", "Sonora", "Sinaloa", "Nayarit", "Jalisco"))
coast.selecc <- stringi::stri_trans_general(str = ents.coast.selecc, id = "Latin-ASCII")

inegi.cost.comm.all  <- readr::read_csv(paste0("~/coastalvulnerability-inputs/processed_data/all_coastal_communities_INEGI.csv")) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_MUN = stringi::stri_trans_general(str = NOM_MUN, id = "Latin-ASCII"), NOM_MUN = toupper(NOM_MUN)) %>% 
  mutate(NOM_LOC = stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC)) %>% 
  keep_when(NOM_ENT %in% coast.selecc)

inegi.cost.mun <- inegi.cost.comm.all %>% 
  distinct(NOM_MUN, CVE_MUN)

permit.files <- list.files(path = here::here("data-raw","permit_data"), full.names = TRUE)
no.permitfiles <- 1:length(permit.files)

permit.data <- lapply(no.permitfiles, extract_permits, permit.files, inegi.cost.comm.all, coast.selecc, locs.pesca, georef.locs.all)

permit.data.rev <- permit.data %>% 
  dplyr::bind_rows()

permit.locs.geo <- permit.data.rev %>% 
  distinct(rnp_code, NOM_ENT, NOM_MUN, NOM_LOC, CVE_LOC, CVE_MUN, CVE_ENT, deci_lat, deci_lon) 

readr::write_csv(permit.locs.geo, here::here("outputs","rnp_fishery_permits.csv"))


```

Get RNP codes from catch records and georreferrence
```{r}

#all coastal communities, including those with no census data
inegi.cost.comm.all  <- readr::read_csv(here::here("data-raw","all_coastal_communities_INEGI.csv")) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_MUN = stringi::stri_trans_general(str = NOM_MUN, id = "Latin-ASCII"), NOM_MUN = toupper(NOM_MUN)) %>% 
  mutate(NOM_LOC = stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC))

#test for duplicates 
dupes.inegi <- inegi.cost.comm.all %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  mutate(dupe = dplyr::n()>1)

georef.locs.all <- readr::read_csv(here::here("outputs","georef_locations.csv")) %>% 
  dplyr::rename(dec_lat_google = deci_lat, dec_lon_google = deci_lon)


#test for duplicates 
dupes.gc <- georef.locs.all %>% 
  group_by(NOM_ENT, NOM_LOC) %>% 
  mutate(dupe = dplyr::n()>1)

#googlesheet to keep track of names that need correction
#vulnerability_tables
    
googlesheets4::gs4_deauth()

 locs.pesca <- googlesheets4::read_sheet("1eJXjwlHqEzSAZaTmE_XyN93fu6EI0I8igRH4AdvXOl8") %>% 
  mutate(NOM_LOC= stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC)) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_LOC_REV= stringi::stri_trans_general(str = NOM_LOC_REV, id = "Latin-ASCII"), NOM_LOC_REV = toupper(NOM_LOC_REV)) %>% 
  mutate(NOM_ENT_REV= stringi::stri_trans_general(str = NOM_ENT_REV, id = "Latin-ASCII"), NOM_ENT_REV = toupper(NOM_ENT_REV)) %>%
   distinct(NOM_LOC, NOM_ENT, NOM_LOC_REV, NOM_ENT_REV) %>% 
   keep_when(!is.na(NOM_LOC_REV))

 
#georeferrenced rnp
permit.locs.geo <-readr::read_csv(here::here("outputs","rnp_fishery_permits.csv"))

 
ents.coast.selecc <- toupper(c("Baja California Sur", "Baja California", "Sonora", "Sinaloa", "Nayarit", "Jalisco"))
coast.selecc <- stringi::stri_trans_general(str = ents.coast.selecc, id = "Latin-ASCII")

permit.locs.geo <- readr::read_csv(here::here("outputs","rnp_fishery_permits.csv")) %>% 
  select(rnp_code, NOM_ENT, NOM_LOC, deci_lat, deci_lon)

catch.files <- list.files(path = here::here("data-raw","fisheries_data"), full.names = TRUE)
no.catchfiles <- 1:length(catch.files)

#get unique georreferenced rnp codes

catch.rnpa <- lapply(no.catchfiles, get_rnpa_catch, catch.files, coast.selecc, locs.pesca, permit.locs.geo, inegi.cost.comm.all, georef.locs.all) 

catch.rnpa.codes <- catch.rnpa %>%
  dplyr::bind_rows() %>% 
  dplyr::bind_rows(permit.locs.geo) %>%
  distinct(rnp_code, NOM_ENT, NOM_LOC, deci_lat, deci_lon)

catch.rnpa.codes %>% dplyr::arrange(NOM_ENT, NOM_LOC) %>% View()



```


Georreference landing records
```{r}

permit.locs.geo <- readr::read_csv(here::here("outputs","rnp_fishery_permits.csv"))

georef.locs.all <- readr::read_csv(here::here("outputs","georef_locations.csv")) %>% 
  dplyr::rename(dec_lat_google = deci_lat, dec_lon_google = deci_lon)


coast.selecc <- "SONORA"

catch.files <- list.files(path = here::here("data-raw","fisheries_data"), full.names = TRUE)
no.catchfiles <- 1:length(catch.files)

#match to rnpa number

catch.rnpa <- lapply(no.catchfiles,get_rnpa_catch, catch.files, coast.selecc, permit.locs.geo, georef.locs.all) 

rnpa.catch.table <- catch.rnpa %>%
  dplyr::bind_rows() %>% 
  mutate(rnp_code = as.character(rnp_code))

catch.rnpa.codes <- rnpa.catch.table %>%
  distinct(rnp_code) 

catch.permit.table <- catch.rnpa.codes %>% 
  dplyr::left_join(permit.table, by = c("rnp_code"))

catch.loc <- catch.permit.table %>% 
  dplyr::left_join(rnpa.catch.table, by = c("rnp_code")) %>% 
  select(-NOM_MUN) %>% 
  dplyr::left_join(inegi.cost.mun, by = "CVE_MUN") %>% 
  group_by(CVE_MUN, CVE_LOC, POBTOT) %>% 
  summarise(tot_catch_mt = sum(tot_weight_kg)/ 1000) %>% 
  mutate(catch_percapita = tot_catch_mt/ POBTOT) 

readr::write_csv(catch.loc, paste0(input.dir,"/processed_data/sensitivity/fishery_catch.csv"))


```




Assign catch to locations

```{r location catch, eval=FALSE, include=FALSE}

#googlesheet to keep track of names that need correction
googlesheets4::gs4_deauth()
locs.pesca <- googlesheets4::read_sheet("1eJXjwlHqEzSAZaTmE_XyN93fu6EI0I8igRH4AdvXOl8")

ents.coast.selecc <- toupper(c("Baja California Sur", "Baja California", "Sonora", "Sinaloa", "Nayarit", "Jalisco", "Yucatán", "Campeche", "Quintana Roo"))
coast.selecc <- stringi::stri_trans_general(str = ents.coast.selecc, id = "Latin-ASCII")
coast.selecc.pac <- c("BAJA CALIFORNIA SUR","BAJA CALIFORNIA","SONORA","SINALOA","NAYARIT","JALISCO")


#all coastal communities, including those with no census data
inegi.cost.comm.all  <- readr::read_csv(paste0(input.dir,"/processed_data/","all_coastal_communities_INEGI.csv")) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_MUN = stringi::stri_trans_general(str = NOM_MUN, id = "Latin-ASCII"), NOM_MUN = toupper(NOM_MUN)) %>% 
  mutate(NOM_LOC = stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC))

catch.files <- list.files(path = paste0(input.dir,"/catch"), full.names = TRUE)
no.catchfiles <- 1:length(catch.files)

catch.locations <- lapply(no.catchfiles, extract_locations, catch.files, coast.selecc, locs.pesca, inegi.cost.comm.all)
  
catch.locs.all <- catch.locations %>% 
  dplyr::bind_rows() %>% 
  distinct(NOM_ENT, NOM_LOC)

#check for duplicates
# catch.locs.inegi.all <-  catch.locs.all %>% 
#   group_by(NOM_ENT, NOM_LOC) %>%
#   mutate(dupe = dplyr::n()>1)
  
catch.locs.all %>% 
    readr::write_csv(paste0(input.dir,"/processed_data/localidades_captura_inegi.csv"))
 
  #subset locations in the pacific and match with landing sites
  catch.locs.pac <- catch.locs.all %>% 
    keep_when(NOM_ENT %in% coast.selecc.pac) %>% 
    dplyr::left_join(loc.pacifico, by = c("NOM_ENT","NOM_LOC"))
     
  #used to find duplicates https://stackoverflow.com/questions/6986657/find-duplicated-rows-based-on-2-columns-in-data-frame-in-r
  #there are multiple landing codes by location, so not using
  # catch.file.sites.table %>% 
  #   group_by(NOM_ENT, NOM_LOC) %>%
  #   mutate(dupe = dplyr::n()>1)
  # 
  
  
   
  
```

