---
title: "permit_data"
author: "Hem Nalini Morzaria-Luna"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r get permit data}
data("georeflocskm")

locs.pesca <- clean_locs_pesca()

ents.coast.selecc <- toupper(c("Baja California Sur", "Baja California", "Sonora", "Sinaloa", "Nayarit", "Jalisco"))
coast.selecc <- stringi::stri_trans_general(str = ents.coast.selecc, id = "Latin-ASCII")

inegi.cost.comm.all  <- readr::read_csv(here::here("inputs","all_coastal_communities_INEGI.csv")) %>% 
  mutate(NOM_ENT= stringi::stri_trans_general(str = NOM_ENT, id = "Latin-ASCII"), NOM_ENT = toupper(NOM_ENT)) %>% 
  mutate(NOM_MUN = stringi::stri_trans_general(str = NOM_MUN, id = "Latin-ASCII"), NOM_MUN = toupper(NOM_MUN)) %>% 
  mutate(NOM_LOC = stringi::stri_trans_general(str = NOM_LOC, id = "Latin-ASCII"), NOM_LOC = toupper(NOM_LOC)) %>% 
  keep_when(NOM_ENT %in% coast.selecc)

inegi.cost.mun <- inegi.cost.comm.all %>% 
  distinct(NOM_MUN, CVE_MUN)

permit.files <- list.files(path = here::here("data-raw","permit_data"), full.names = TRUE)
no.permitfiles <- 1:length(permit.files)

permit.data <- lapply(no.permitfiles, extract_permits, permit.files, coast.selecc, locs.pesca, georeflocskm)

permitdata <- permit.data %>% 
  dplyr::bind_rows() %>% 
  distinct(rnp_code, NOM_LOC, NOM_ENT, deci_lat, deci_lon, fishery_office, fishery_office_ent, distance_km)



readr::write_csv(permitdata, here::here("outputs","rnp_fishery_permits.csv"))


```
